apiVersion: v1
kind: Service
metadata:
  name : myapp-service
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    app: my-app
    costcenter: amer
    location: aus
    type: front-end

