apiVersion: v1
kind: Service
metadata:
  name : backend
spec:
  type: ClusterIP
  ports:
    - nodePort: 30002
      port: 80
      targetPort: 80
  selector:
    app: my-app
    costcenter: amer
    location: aus
    type: front-end